require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - bin/*
    - db/schema.rb
    -  vendor/**/*

Style/Documentation:
  Enabled: false

Metrics:
  Exclude:
    - db/migrate/*

Rails/NotNullColumn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*/**

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
