require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - bin/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics:
  Exclude:
    - db/migrate/*

Rails/NotNullColumn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*/**

RSpec/MultipleMemoizedHelpers:
  Enabled: false
