version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: timescale/timescaledb-postgis:latest-pg13
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: albuvideo_api_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: ""
      - image: circleci/redis:alpine
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install FFmpeg
          command: sudo apt update && sudo apt install -y ffmpeg
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

  rubocop:
    docker:
      - image: cimg/ruby:3.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  Rubocop:
    jobs:
      - rubocop
  RSpec:
    jobs:
      - rspec
