apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
spec:
  rules:
    - host: "api.albuvideo.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: albuvideo-api
                port:
                  number: 80
