apiVersion: apps/v1
kind: Deployment
metadata:
  name: albuvideo-api-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: albuvideo-api-worker
  template:
    metadata:
      labels:
        app: albuvideo-api-worker
    spec:
      containers:
        - name: albuvideo-api
          imagePullPolicy: Always
          image: gcr.io/albucode/albuvideo-api:latest
          command: ["bundle"]
          args: ["exec", "sidekiq"]
          env:
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: RAILS_ENV
              value: "production"
            - name: SECRET_KEY_BASE
              value: "production-key"
            - name: ALBUVIDEO_API_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: albuvideo-secrets
                  key: username
            - name: ALBUVIDEO_API_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: albuvideo-secrets
                  key: password
            - name: ALBUVIDEO_API_DATABASE_DATABASE
              value: "albuvideo_api_production"
            - name: ALBUVIDEO_API_DATABASE_HOST
              value: "postgres"
            - name: ALBUVIDEO_API_DATABASE_PORT
              value: "5432"
            - name: REDIS_URL
              value: "redis://10.165.6.11:6379"
          ports:
            - containerPort: 3000
              protocol: TCP
