apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albuvideo-api
      tier: database
  template:
    metadata:
      name: redis
      labels:
        app: albuvideo-api
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
