kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-persistentvolume
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
